apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 8501 
    targetPort: 8501 
    nodePort: 31000 
  type: NodePort  
