apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 8501  # Port interne
    targetPort: 8501  # Port exposé par le conteneur
    nodePort: 31000  # Port externe pour accéder au service depuis le nœud
  type: NodePort  # Permet l'accès externe au service
